<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Genre extends Model
{
    use HasFactory;

    public const TYPE_AUTO_GENERATED_JAPANESE = 'auto_generated_japanese';
    public const TYPE_AUTO_GENERATED_ENGLISH = 'auto_generated_english';
    public const TYPE_CUSTOM = 'custom';

    public const LANGUAGE_ENGLISH = 'en';
    public const LANGUAGE_JAPANESE = 'jp';

    protected $fillable = [
        'group_id',
        'title',
        'description',
        'order',
        'type',
        'language',
    ];

    public function group(): BelongsTo
    {
        return $this->belongsTo(GenreGroup::class, 'group_id');
    }

    public function products(): BelongsToMany
    {
        return $this->belongsToMany(Product::class)->withTimestamps();
    }

    public function scopeCustom(Builder $query): void
    {
        $query->where('type', self::TYPE_CUSTOM);
    }

    public function scopeAutoGeneratedEnglish(Builder $query): void
    {
        $query->where('type', self::TYPE_AUTO_GENERATED_ENGLISH);
    }

    public function scopeAutoGeneratedJapanese(Builder $query): void
    {
        $query->where('type', self::TYPE_AUTO_GENERATED_JAPANESE);
    }

    public static function resolveIdsFromTitles(array $titles, string $type, string $language): array
    {
        return collect($titles)
            ->map(fn (mixed $title) => self::normalizeTitle($title))
            ->filter()
            ->map(fn (string $title) => self::resolveByTitle($title, $type, $language)->getKey())
            ->unique()
            ->values()
            ->all();
    }

    public static function resolveByTitle(string $title, string $type, string $language): self
    {
        $genre = self::query()->where('title', $title)->first();

        if ($genre === null) {
            return self::query()->create([
                'group_id' => null,
                'title' => $title,
                'description' => null,
                'order' => null,
                'type' => $type,
                'language' => $language,
            ]);
        }

        if ($genre->shouldPromoteTo($type)) {
            $genre->forceFill([
                'type' => $type,
                'language' => $language,
            ])->save();
        }

        return $genre;
    }

    private function shouldPromoteTo(string $preferredType): bool
    {
        return in_array($preferredType, [
            self::TYPE_AUTO_GENERATED_JAPANESE,
            self::TYPE_AUTO_GENERATED_ENGLISH,
        ], true) && $this->type === self::TYPE_CUSTOM;
    }

    private static function normalizeTitle(mixed $title): ?string
    {
        if ($title === null) {
            return null;
        }

        $normalizedTitle = trim((string) $title);

        return $normalizedTitle === '' ? null : $normalizedTitle;
    }
}
